### ISSUE TITLE
1.0.4 IE11 functionality is broken

### ISSUE THREAD

**Issue by Vackysan** [devstark-com/vue-textarea-autosize#11]
The "_Implement 'important' prop handling_" commit broke IE11 functionality.

The "this.$el.style.setProperty('height', heightVal, important)" in the resize() function silently fails on IE11 when "important" is undefined.

Consider modifying to (tested on my end):
```
if (important) {
      this.$el.style.setProperty('height', heightVal, important);
} else {
      this.$el.style.setProperty('height', heightVal);
}
```

**Comment by guille-moe** [comment]
broken on Edge too, turn `:important` to `true` fix it.
