### ISSUE TITLE
Attach events to textarea

### ISSUE THREAD

**Issue by jwynveen** [devstark-com/vue-textarea-autosize#12]
I want to handle an event `@keyup.enter`, but the component doesn't pass along attributes. Can this be added to the `textarea` tag in the component:

```
<textarea 
    ...
    v-bind="$attrs"
></textarea>
```

This allows me to use the component in my code like so:

```
<textarea-autosize
    class="message-text"
    v-model="messageInput"
    :max-height="100"
    @keyup.enter="sendMessage"
  ></textarea-autosize>
```

**Comment by Saymon-biz** [comment]
I think you should use `@keyup.enter.native`
https://vuejs.org/v2/guide/migration.html#Listening-for-Native-Events-on-Components-with-v-on-changed
