### ISSUE TITLE
autosize not working on Edge, IE11

### ISSUE THREAD

**Issue by danielSONCCO** [devstark-com/vue-textarea-autosize#15]
https://github.com/devstark-com/vue-textarea-autosize/blob/720ef40ce587608e65d767c9d8d6aca7a1674f10/src/components/TextareaAutosize.vue#L135
I think the issue comes from lines like this one, it seems that on IE11 setProperty doesn't work with 3 arguments, doing setProperty("height", heightVal) works in local

**Comment by Saymon-biz** [comment]
@danielSONCCO fixed in #17 you just need to update the plugin to 1.1.1
