### ISSUE TITLE
[Feature] Multiline placeholder in safari/opera

### ISSUE THREAD

**Issue by franciscolourenco** [devstark-com/vue-textarea-autosize#18]
Safari and opera don't render multi-line placeholders.

vue-textarea-autosize could support this by implementing a fake placeholder.

**Comment by Saymon-biz** [comment]
@franciscolourenco this particular component was born to be dead simple, lightweight and cover some pretty simple cases when you want to avoid adding large or medium-size dependencies. But there are many more flexible alternatives. Try to look at Element-UI, Vuetify, etc.
