### ISSUE TITLE
Why is there vue-textarea-autosize.css

### ISSUE THREAD

**Issue by adamdavidcz** [devstark-com/vue-textarea-autosize#2]
Hello,

I got compilation error from webpack on **vue-textarea-autosize.css** probably because I don't have any CSS loaders. Question is why is there such style included?

**Comment by Saymon-biz** [comment]
@adamdavidcz It was an artifact of the vue-cli template we used and it's already removed. Try again!

**Comment by adamdavidcz** [comment]
@Saymon-biz Thank you!
