### ISSUE TITLE
Initial height not correct

### ISSUE THREAD

**Issue by Loschcode** [devstark-com/vue-textarea-autosize#21]
I've got some styling in my CSS so the textarea looks like a simple text input

```
textarea {
  height: 3em;
}
```

When i apply `<textarea-autosize>` my styling is ignored and replaced by specific pixel height, which I believe is normal behavior, and manipulating the options of this library doesn't seem to fix the problem, the initial height is wrong and can't be adjusted.

<img width="250" alt="Screenshot 2019-05-01 11 58 38" src="https://user-images.githubusercontent.com/6666570/57026743-792c5f00-6c08-11e9-97c3-f8bc6b4eaa4b.png">

(it should be half of the height seen on the screenshot)

**Comment by Invulner** [comment]
@Loschcode try this one https://github.com/devstark-com/vue-textarea-autosize/issues/8#issuecomment-448544641
