### ISSUE TITLE
this.$refs.someName.$el.focus() not working

### ISSUE THREAD

**Issue by sujeshthekkepatt** [devstark-com/vue-textarea-autosize#4]
the focus method not working

**Comment by Saymon-biz** [comment]
@sujeshthekkepatt Do you can provide us some reproduction repo or fiddle link?

**Comment by Saymon-biz** [comment]
@sujeshthekkepatt seems like it's not an issue, see [reproduction](https://codesandbox.io/s/jv5w1kzn7w)
