### ISSUE TITLE
Make the newly inserted css styles !important

### ISSUE THREAD

**Issue by gijo-varghese** [devstark-com/vue-textarea-autosize#5]
`vue-textarea-autosize` add the following properties to textarea right:     
```
{
    resize: none;
    overflow: hidden;
    height: 32px;
}
```

For my project, I've to use http://cleanslatecss.com/ which make every css !important. So the height is already set as !important and hence `vue-textarea-autosize`  isn't working for me. Is there any way to make it !important?

**Comment by Saymon-biz** [comment]
@gijo-varghese Yeah, I'm gonna add the separate prop `important` which will expect `Boolean` or `Array`, so there will be an ability to:

- add `!important` to all properties via `<textarea-autosize :important="true" ...` or just `<textarea-autosize important ...`
- add `!important` to particular properties e.g. `<textarea-autosize :important="['resize', 'height']" ...`

**Comment by gijo-varghese** [comment]
@Saymon-biz that would be cool. Can you please do it asap. Pleaseeee. I really love this library.

**Comment by Saymon-biz** [comment]
@gijo-varghese I'll be able to do it in 7-8 hours or so

**Comment by gijo-varghese** [comment]
Awesome :)

**Comment by Saymon-biz** [comment]
@gijo-varghese the requested feature is in the `feature/add_prop_important` branch. Please, try it out and let me know if that's what we need. If yes I'll update version and publish to npm. [Here is an article](https://medium.com/@jonchurch/use-github-branch-as-dependency-in-package-json-5eb609c81f1a) on how to use Github branch as dependency in package.json

**Comment by gijo-varghese** [comment]
Ok. Let me try that

**Comment by gijo-varghese** [comment]
and my package.json file:
```
"dependencies": {
    ....
    "vue-textarea-autosize": "devstark-com/vue-textarea-autosize#feature/add_prop_important"
  },
```

**Comment by Saymon-biz** [comment]
@gijo-varghese delete folder in `node_modules`, reinstall package and try again

**Comment by gijo-varghese** [comment]
@Saymon-biz ah. Its now working. Perfect!! Can you pls merge it to master and publish to npm...

**Comment by Saymon-biz** [comment]
@gijo-varghese done!

**Comment by gijo-varghese** [comment]
Thanks a lot :)
