### ISSUE TITLE
No. of rows not documented

### ISSUE THREAD

**Issue by gijo-varghese** [devstark-com/vue-textarea-autosize#6]
I was having some trouble to set the initial no. of rows. After looking into the source code I figured out that there is `:rows="1"` but its not documented anywhere. Can you please add it. Will be helpful for many

**Comment by Saymon-biz** [comment]
There is no any initial no. of rows in our sources. You can just add it. e.g.  `<textarea-autosize rows="10"...`

**Comment by Saymon-biz** [comment]
See `App.vue` [here](https://codesandbox.io/s/1z1222jpl)
