### ISSUE TITLE
Bootstrap collapse problem

### ISSUE THREAD

**Issue by alexander-f-ysbm** [devstark-com/vue-textarea-autosize#7]
Hello, if I use the plugin inside the bootstrap collapse, then the height is not set automatically until that moment, until I click on the text box and then even after closing and opening the collapse everything works correctly. How can I initially press it so that the size is set?

I tried to click on the field when the component is mounted, but it did not help I think that my trigger click does not work
```
mounted () {
     this.$refs.textarea.$el.click();
}
```
* If you initially set the collapse open, everything is displayed correctly

**Comment by Saymon-biz** [comment]
@alexander-f-ysbm can you put a simple example with reproduction e.g. at [https://codesandbox.io/](https://codesandbox.io/)
so I'll be able to reproduce this issue and figure out a solution

**Comment by alexander-f-ysbm** [comment]
I found the error it was due to the fact that it's impossible to get the height of the element that is hidden. Unfortunately I can not emit this problem in the "kodesandbox" because I get an error "Failed to mount component: template or render function not defined".

**Comment by Saymon-biz** [comment]
Ok, let's see step by step, provide reproduction link with the error you got

**Comment by alexander-f-ysbm** [comment]
try to create a bootstrap collapse, when you expand it you will notice that the text field has not set the desired height.
`<p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Link with href
  </a>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <textarea-autosize
      placeholder="Type something here..." ref="someName"
      v-model="someValue" :min-height="30" :max-height="350"
     ></textarea-autosize>
  </div>
</div>`

**Comment by Saymon-biz** [comment]
Returning to the issue - I've realized that actually, you just shouldn't render the component until it becomes visible. This way you won't have to solve this problem. It just won't exist
