### ISSUE TITLE
Automatic scroll to top window on type

### ISSUE THREAD

**Issue by joppehoekstra** [devstark-com/vue-textarea-autosize#9]
When the textarea becomes larger than the user window, the page will scroll to the top when you type.

**Comment by hallidev** [comment]
Did you ever find a solution to this issue? I'm experiencing the same thing

**Comment by yangzhuoze** [comment]
Experiencing the same thing too, is there any solution other than this lib?

**Comment by Saymon-biz** [comment]
@joppehoekstra @hallidev @yangzhuoze it was a deliberate decision to leave that out of this component. Moreover, you can see the same behavior here https://element.eleme.io/#/en-US/component/input#autosize-textarea and here https://vuetifyjs.com/en/components/textarea#playground
Actually, there are too many different use-cases so there couldn't be a universal solution to satisfy all of them. The implementation should depend on the particular use-case so it shouldn't be provided out of the box and you have to handle it by yourself using `min-height` and `max-height` bound to some states in a parent component.
